[package]
name = "artist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "2.0.0"
enigo = "0.1.3"
image = "0.25.1"
xcap = "0.0.8"
